apiVersion: v2
name: istio-stack
description: Istio Service Mesh for Kubernetes
type: application
version: 1.0.0
appVersion: "1.24.2"

dependencies:
  - name: base
    version: 1.24.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: istiod
    version: 1.24.2
    repository: https://istio-release.storage.googleapis.com/charts
  - name: gateway
    version: 1.24.2
    repository: https://istio-release.storage.googleapis.com/charts
    condition: gateway.enabled
