apiVersion: v2
name: cnpg-operator
description: CloudNativePG Operator for PostgreSQL management
type: application
version: 1.0.0
dependencies:
  - name: cloudnative-pg
    version: 0.23.0
    repository: https://cloudnative-pg.github.io/charts
