{{- if .Values.gateway.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: keycloak-gateway
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.gateway.hostname }}
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: keycloak-vs
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  hosts:
  - {{ .Values.gateway.hostname }}
  gateways:
  - {{ .Values.namespace.name }}/keycloak-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: keycloak-instance-service
        port:
          number: 8080
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: keycloak-dr
  namespace: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  host: keycloak-instance-service
  trafficPolicy:
    tls:
      mode: DISABLE
{{- end }}
