apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak-instance
  namespace: {{ .Values.namespace.name }}
spec:
  instances: {{ .Values.keycloak.replicas }}
  image: {{ .Values.keycloak.image.registry }}/{{ .Values.keycloak.image.repository }}:{{ .Values.keycloak.image.tag }}
  startOptimized: {{ .Values.keycloak.startOptimized }}
  resources:
    requests:
      memory: {{ .Values.keycloak.resources.requests.memory }}
      cpu: {{ .Values.keycloak.resources.requests.cpu }}
    limits:
      memory: {{ .Values.keycloak.resources.limits.memory }}
      cpu: {{ .Values.keycloak.resources.limits.cpu }}
  http:
    httpEnabled: {{ .Values.keycloak.httpEnabled }}
  db:
    vendor: postgres
    host: keycloak-db-rw
    usernameSecret:
      name: keycloak-db-app
      key: username
    passwordSecret:
      name: keycloak-db-app
      key: password
  hostname:
    hostname: {{ .Values.keycloak.hostname }}
    strict: false
  ingress:
    enabled: false
  proxy:
    headers: xforwarded
  additionalOptions:
    - name: http-enabled
      value: {{ .Values.keycloak.httpEnabled | quote }}
    - name: hostname-strict-https
      value: "false"
{{- if .Values.logging.enabled }}
    - name: log-level
      value: {{ .Values.logging.keycloak.level | quote }}
    - name: log-console-output
      value: {{ .Values.logging.format | quote }}
{{- end }}
