{{- if .Values.keycloak.init.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keycloak-init-sa
  namespace: {{ .Values.namespace.name }}
  labels:
    app: keycloak-init
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: keycloak-init-role
  namespace: {{ .Values.namespace.name }}
  labels:
    app: keycloak-init
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["keycloak-instance-initial-admin"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: keycloak-init-binding
  namespace: {{ .Values.namespace.name }}
  labels:
    app: keycloak-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keycloak-init-role
subjects:
- kind: ServiceAccount
  name: keycloak-init-sa
  namespace: {{ .Values.namespace.name }}
{{- end }}
