apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username }}
  password: {{ .Values.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-initial-admin
  namespace: {{ .Values.namespace.name }}
type: Opaque
stringData:
  username: {{ .Values.keycloak.admin.username }}
  password: {{ .Values.keycloak.admin.password }}
