apiVersion: v2
name: iam-stack
description: Keycloak IAM Stack with CloudNativePG
type: application
version: 1.0.0
appVersion: "26.4.2"
dependencies:
  - name: cloudnative-pg
    version: 0.23.0
    repository: https://cloudnative-pg.github.io/charts
