apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    name: {{ .Values.namespace.name }}
    istio-injection: enabled
