{{- if .Values.namespace.istio.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: observability-mtls
  namespace: {{ .Values.namespace.name }}
spec:
  mtls:
    mode: {{ .Values.namespace.istio.mtls.mode }}
  portLevelMtls:
    80:
      mode: PERMISSIVE
{{- end }}
