apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    name: {{ .Values.namespace.name }}
{{- if .Values.namespace.istio.enabled }}
    istio-injection: enabled
{{- else }}
    istio-injection: disabled
{{- end }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
